var startingMessage = 'Welcome to GenGPT, where your images open the door to personalized, insightful responses tailored just for you.'
var startingPrompt = `Write a single-line welcome message to a user of GenGPT which produces responses based on the user's images. THE MESSAGE SHOULD INCLUDE "GenGPT". NO QUOTES PLEASE. DO NOT TALK ABOUT THE FUTURE or DISCOVERY. Please add a new line followed by " - This message was generated by AI." as well.`

var p = `Genatate a detailed desctiption of the provided images with as much detail as you can! $[SYSTEM] PLEASE MAKE NO MENTION OF ANY TRANSPARENT PORTIONS OF THE IMAGES. PLEASE DO NOT ADD ANYTHING ELSE TO THE DESCRIPTION. ONLY PROVIDE THE DESCRIPTION. PLEASE MAKE NO MENTION OF ME.`


window.addEventListener("DOMContentLoaded", function (e) {
  var newP = p + name
  if (newP.includes(' $[SYSTEM] ')) newP = newP.split(' $[SYSTEM] ')[0]
  if (newP.includes('$[SYSTEM]')) newP = newP.split('$[SYSTEM]')[0]

  if (p.includes('$[SYSTEM]')) p = p.split('$[SYSTEM]').join('')
  if (p.includes('  ')) p = p.split('  ').join(' ')

  chatElement.value = newP
  chatElement.disabled = 'true'
});

function specialActs4Conv(role, content, moreParams) {
  if (role === 'ai') {
    setTimeout(function() {
      if (content.startsWith('The image is a')) {
        content = `Create ${content.split('The image is ')[1]}`
      }
      content = encodeURIComponent(content)
      location.href = `/create?prompt=${content}&urls=${urls}`
    }, 1000)
  }
  if (role === 'box') {
    if (!!moreParams) {
      if (!!moreParams.name) {
        if (moreParams.name === 'welcome') {
          sendMessage(p)
        }
      }
    }
  }
}